spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console
keycloak:
  realm: Demo
  auth-server-url: ${keycloak_server_url}
  ssl-required: external
  resource: ${demo_client2_id}
  credentials:
    secret: ${demo_client2_secret}
#  use-resource-role-mappings: true
  bearer-only: off
  policy-enforcer-config:
    enforcement-mode: enforcing
  security-constraints:
    - authRoles:
        - '*'
      securityCollections:
        - patterns:
            - /*
  principal-attribute: preferred_username

logging:
  level:
    org.keycloak: DEBUG
