spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console
keycloak:
  realm: Demo
  auth-server-url: ${keycloak_server_url}
  ssl-required: external
  resource: ${demo_client_id}
  credentials:
    secret: ${democ_lient_secret}
  use-resource-role-mappings: true
  bearer-only: true